---
title: "Tutorials"
output: html_document
---
[Home](/)

The "10 minute series" tutorials listed below are edited and reformatted from the handouts of my numerous talks at a seminar series organized by Agile Community of Practice (CoP) group.
  
The CoP audience was composed of working professionals from acedemia, scientists at federal govt agencies and contractors from private sector working on DigitalGov initiative projects.
  
This is a side project so it may take me another month or two to post tutorials of all the 20+ talks I have given to the CoP group in past five years.

The outline of the tutorials are below:

**Section I: Basics**

1. [Python Data Structures in 10 minutes](http://jaympatel.com/pages/Python_Data_Structures_in_10_Minutes.html)  
  - Tuple  
  - List  
  - Dictionaries or Dicts  
  - Set  
  - Numpy  
  - Pandas Series  
  - Pandas DataFrame  
  
2. Object Oriented Programming (OO) in Python in 10 Minutes

3. R Data Structures in 10 minutes
  
4. [Perspectives on Object oriented Programming in R](http://jaympatel.com/pages/OO_in_R.html)  
  - S3  
  - S4  
  - Reference Class  
  - Base  
  - R Community Reccomendations  
  - What's Better for New Projects: S3 or S4?  
  
5. Distributing R Scripts as Packages
  
6. Visualization in R and Python
- [Wordcloud in python](/pages/wordcloud.html)
- Matplotlib  
- GGPlot2  

**Section II: Getting Data from Databases and Web Services**

7. Relational Databases  
 - MySQL  
 - PostgreSQL 
 - SQLite  
  
8. NoSQL Databases  
- MongoDB  
- Apache Cassandra  

9. Rest Web Services  
  
**Section III: Advanced Topics**
  
10. Big Data Analytics  
- Apache Spark  
- Apache Hadoop  
- Apache Hive  
- Apache Pig  
- Apache Kafka  
  
11. Theoretical Considerations for Common Machine Learning Algorithms  

12. Practical Machine Learning in Python  

**Appendix**

[Git in 10 Minutes](http://jaympatel.com/pages/Git_in_10_minutes.html)
